name: Build and Deploy

on:
    push:
        branches:
            -master 

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            uses: actions/checkout@master
          
    

    

